---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: console
  annotations:
    kubernetes.io/service-account.name: console
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-role-binding
subjects:
- kind: ServiceAccount
  name: console
  namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      serviceAccountName: console
      containers:
        - name: console
          image: quay.io/openshift/origin-console:4.20.0
          env:
            - name: BRIDGE_USER_AUTH
              value: disabled
            - name: BRIDGE_K8S_MODE
              value: off-cluster
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
              value: https://kubernetes.default
            - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
              value: "true"
            - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: console
                  key: token
---
apiVersion: v1
kind: Service
metadata:
  name: console
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 32080
  selector:
    app: console
