apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: cartservice
