apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aspnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: registry.gitlab.com/solve-x-kubernetes/aspnetapp:main
        ports:
        - containerPort: 8080
        env:
        - name: Serilog__WriteTo__0__Args__formatter
          value: "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact"
